language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm

services:
    - mysql

before_script:
    - composer install --prefer-source
    - mysql -u root -e "CREATE DATABASE rsfilesystem;"
    - mysql -u root -e "CREATE USER 'rsfilesystem'@'localhost' IDENTIFIED BY '';"
    - mysql -u root -e "GRANT ALL PRIVILEGES ON rsfilesystem.* TO 'rsfilesystem'@'localhost' WITH GRANT OPTION;"

script:
    - vendor/bin/codecept run
